/** Define ids for each page. */
export const PAGE_IDS = {
  DISCUSS: 'discuss',
  LANDING: 'landing',
  HOME: 'home',
  LIST_FACULTY_ADMIN: 'list-faculty-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  EDIT_ROOM: 'edit-room',
  LIST_ROOM: 'list-room',
  PROFILE: 'profile',
  LIST_ROOM_ADMIN: 'list-room-admin',
  FACULTY: 'faculty',
  EDIT_FACULTY_PROFILE: 'edit-faculty-profile',
  ROOM_DETAILS: 'room-details',
  CLUB: 'club',
  TECH: 'tech',
  STAFF_PROFILE: 'staff-profile',
};
