/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  DISCUSS: 'discuss',
  EDIT_STUFF: 'edit-stuff',
  LANDING: 'landing',
  HOME: 'home',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  LIST_FACULTY_ADMIN: 'list-faculty-admin',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  EDIT_ROOM: 'edit-room',
  LIST_ROOM: 'list-room',
  PROFILE: 'profile',
  LIST_ROOM_ADMIN: 'list-room-admin',
  FACULTY: 'faculty',
  EDIT_FACULTY_PROFILE: 'edit-faculty-profile',
  ROOM_DETAILS: 'room-details',
  CLUB: 'club',
};
